//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.24 at 12:44:09 PM EST 
//


package edu.harvard.mcz.edec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.mcz.edec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EDecFile_QNAME = new QName("http://www.example.org/eDecXMLSchema", "eDecFile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.mcz.edec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Species }
     * 
     */
    public Species createSpecies() {
        return new Species();
    }

    /**
     * Create an instance of {@link Core }
     * 
     */
    public Core createCore() {
        return new Core();
    }

    /**
     * Create an instance of {@link EDec }
     * 
     */
    public EDec createEDec() {
        return new EDec();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EDec }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/eDecXMLSchema", name = "eDecFile")
    public JAXBElement<EDec> createEDecFile(EDec value) {
        return new JAXBElement<EDec>(_EDecFile_QNAME, EDec.class, null, value);
    }

}
